version: '3.1'

services:

  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9018:9018
    environment:
      VIRTUAL_HOST: chat.devent.kr
      LETSENCRYPT_HOST: chat.devent.kr
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"
