format_version: 10
pipelines:
  facemesh:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    tracking_tool:
      link: https://github.com/testprocess/facemesh/issues/${ID}
      regex: '##(/d+)'
    display_order: -1
    materials:
      git-bbdeec3:
        git: https://github.com/testprocess/facemesh
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker-compose:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - compose
                - build
                command: docker
                run_if: passed
            - exec:
                arguments:
                - compose
                - up
                - -d
                command: docker
                run_if: passed
